### ISSUE TITLE
Can't easily remove npm-completion from my computer

### ISSUE THREAD

**Issue by ghost** [Jephuff/npm-completion#1]
Hello,

http://i.imgur.com/znkvV3o.png

**Comment by Jephuff** [comment]
Hi @amezarashi97, is that in the same shell that you uninstalled it from? if so, try opening a new terminal and see if it persists.

If it does, that means the lines that load it are still in your .bashrc or .bash_profile. If you could post the results of `cat ~/.bash_profile | grep npm-completion` and `cat ~/.bashrc | grep npm-completion` I can take a look into why it didn't remove them 👍

**Comment by ghost** [comment]
Yosh here you go:


```
Romain@Romain-PC /cygdrive/c/Users/Romain
$ cat ~/.bash_profile | grep npm-completion

Romain@Romain-PC /cygdrive/c/Users/Romain
$ cat ~/.bashrc | grep npm-completion
# added for npm-completion https://github.com/Jephuff/npm-bash-completion
PATH_TO_NPM_COMPLETION="/cygdrive/c/Users/Romain/AppData/Roaming/npm/node_modules/npm-completion"
source $PATH_TO_NPM_COMPLETION/npm-completion.sh

Romain@Romain-PC /cygdrive/c/Users/Romain
$
```

**Comment by Jephuff** [comment]
Thanks! Looks like it did fail to remove itself so I will look into why that happened. 

But for your case you will need to remove those three lines manually from your .bashrc file.
