### ISSUE TITLE
After using npm-completion console breaks

### ISSUE THREAD

**Issue by theexplay** [Jephuff/npm-completion#4]
Hello!
I have Ubuntu 16.04
After using npm-completion console breaks, for example:
`$ npm run storybook (with autocomplete)`
When i stop process with ctrl+c, and trying to type any letters becomes invisible (like when u typing password in sudo).
For example i still can type anything and even start process, but i don't see letters and it's little annoying.
After restart console all works properly until i use auto completion again.

P.S. Sorry for my english

**Comment by Jephuff** [comment]
@theexplay thanks for this issue! I had thought this was a webpack issue, but after investigating I found the issue with npm-completion. This will be fixed in version 2.0.3 :)
