### ISSUE TITLE
Small problem with ~/.bashrc 

### ISSUE THREAD

**Issue by geokal** [Jephuff/npm-completion#5]
Not quite a bug, but I've added the following on my ~/bashrc:

`# added for npm-completion https://github.com/Jephuff/npm-bash-completion
PATH=$PATH:"/usr/local/bin":"/usr/local/bin":"/usr/local/bin"
INCLUDE_YARN_COMPLETION=false
PATH_TO_NPM_COMPLETION="/usr/local/bin/../lib/node_modules/npm-completion" && cd /$PATH_TO_NPM_COMPLETION && ./update
source $PATH_TO_NPM_COMPLETION/npm-completion.sh`

and now every time I open a new terminal, the bash opens inside npm-completion's  dir

**Comment by geokal** [comment]
I moved the above lines to ~/bash_profile  with `&& cd ~` added. you can delete the ticket. :)

**Comment by Jephuff** [comment]
These lines you might not want in your .bashrc  or .bash_profile file, the update command pulls from the git repo to get the latest package names so you might not want that happening for every new terminal (though it does mean they will always be fresh:) )
```
PATH=$PATH:"/usr/local/bin":"/usr/local/bin":"/usr/local/bin"
PATH_TO_NPM_COMPLETION="/usr/local/bin/../lib/node_modules/npm-completion" && cd /$PATH_TO_NPM_COMPLETION && ./update
```

Regardless though I will update the example command to not change the directory :)
