### ISSUE TITLE
git bash for windows

### ISSUE THREAD

**Issue by rachidlamouri** [Jephuff/npm-completion#6]
I was wondering if this package is supposed to work with git bash on windows. It installs on windows and the following line runs as expected
`npm run <partial script name><tab>`

However if my npm script requires a filepath input the filepath won't tab complete

`npm run dosomething <partial file or foldername><tab>` does not autocomplete the path

**Comment by Jephuff** [comment]
Hi @RachiLam this wasn't actually unique to windows, I just hadn't added completion for file paths after scripts. I just added that in 2.0.3, I don't have a windows machine currently, if you could verify this works that would be great :) 

Thanks!

**Comment by rachidlamouri** [comment]
Hi @Jephuff thanks for the quick response! I did the following steps and it seems that it resolves files but does not complete folders as expected

1. I cloned the repository
2. verified version 2.0.3
3. manually ran ./setup (does setting the postinstall script to "bash ./setup" work on all platforms?)
4. restarted git-bash terminal
5. Resolving a script and file: `npm run post<tab> npm-comp<tab>` produces `npm run postinstall npm-completion.sh ` as expected (with a space at the end)
6. Resolving a script and folder: `npm run post<tab> npm-pack<tab>` produces `npm run postinstall npm-package-names ` (with a space at the end) instead of `npm run postinstall npm-package-names/` (with a '/' and no space at the end)

With folder setup:
abc
 | ->def
`npm run post<tab> abc/<tab>` produces `npm run postinstall abc/def ` instead of `npm run postinstall abc/def/`

I don't know bash programming so I can't suggest any code changes without doing some research. I hope this helps.

**Comment by Jephuff** [comment]
ahhh oops, ok published version 2.0.4, this should complete in the expected way.
